platform :ios, '11.0'

target 'Cosmic Ray' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cosmic Ray
  pod 'Alamofire', '~> 5.4'
  pod 'KeychainAccess', '~> 4.2'

end
